### ISSUE TITLE
Remote device should probably return remote:driver= and remote= to work with make

### ISSUE THREAD

**Issue by cjcliffe** [pothosware/SoapyRemote#11]
When querying the device remotely (RTLSDR at least, I may have missed something in the module?), the only way I know it's an rtlsdr is by checking known parameters and the 'rtl' index key.  It would be handy to automatically return the remote:driver and remote option as well; right now I just get driver=remote and if you pass it directly to make() it won't work without setting those two as well.

**Comment by guruofquality** [comment]
Ahh, good point. To be consistent, SoapyRemote's discovery function should be preserving those keys.

**Comment by guruofquality** [comment]
Should work now

**Comment by cjcliffe** [comment]
Excellent, tested and working here on Raspberry Pi + RTLSDR & OSX
