### ISSUE TITLE
Unable to set SoapyRemote thread priority unless Server running as root

### ISSUE THREAD

**Issue by gedger** [pothosware/SoapyRemote#19]
SoapyRemote does't appear to be able to set it's own thread priority as it gives a warning

 `[WARNING] Set thread priority 0.5 failed: Operation not permitted`

If the Server is run as root then warning goes away.

**Comment by guruofquality** [comment]
Its a linux security limits thing. The only options are to run as root or to edit the security limits. Some notes here: https://github.com/pothosware/SoapyRemote/wiki#remotepriority

**Comment by gedger** [comment]
Thanks, sorry missed this in the documentation.
