### ISSUE TITLE
Identification of multiple devices

### ISSUE THREAD

**Issue by wtfuzz** [pothosware/SoapyRemote#28]
I have multiple SDRs attached to a dedicated SoapySDRServer on my LAN, however clients show identical names for all attached devices.

It would be useful to be able to specify a user defined names for each SDR by USB bus/dev identifiers.

**Comment by guruofquality** [comment]
There is a "label" convention where the discovery routine provides the label key in the discovered dictionary. This label is used in guis to provide dropdowns (like gqrx, cubicsdr, pothossdr blocks). This label would also show up in a find() operation to uniquely identify the device. Labels are just a string, and its up to the implementation, but its typically serial number, product name, maybe revision.

What devices are using? if its something I maintain, I can make sure that it has this label. If not I recommend adding this if possible. I hope that helps. You can find some more information here: https://twitter.com/pothosware/status/828173445808549888
