### ISSUE TITLE
[ERROR] SoapySDR::loadModule(...)   duplicate entry for remote (...)

### ISSUE THREAD

**Issue by Davem734** [pothosware/SoapyRemote#31]
Following this procedure to install SDRplay and CubicSDR on a 32bit Ubuntu 14.04 system:

http://www.sdrplay.com/docs/SDRplay_non_Windows_Flow.pdf

I get the following error when running:

```
$ SoapySDRUtil --find=sdrplay
######################################################
## Soapy SDR -- the SDR abstraction library
######################################################

linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.010.002.000-release

[ERROR] SoapySDR::loadModule(/usr/local/lib/SoapySDR/modules0.6/libremoteSupport.so)
  duplicate entry for remote (/usr/lib/i386-linux-gnu/SoapySDR/modules0.6/libremoteSupport.so)
Found device 0
  driver = miri
  label = Mirics MSi2500 default (e.g. VTX3D card)
  miri = 0

```
There are two copies of Soapyremote. One was installed from the repository. But I could not get CubicSDR to complie unless I also installed Soapy from Github. Is there a way that I can specify which Soapy should be used with SDRplay? If I try to uninstall the version of Soapy from the repository then it wants to uninstall most of the other SDR software that I installed from the repo. Seems a bit strange that it errors when it finds more than one, I would think that it should just use the first one it finds. I still get the error when I am using RTLSDR. So I assume it is defaulting to the repo version that does not have SDRplay support. Is there a way that I can specify which Soapy should be used?

**Comment by guruofquality** [comment]
> But I could not get CubicSDR to complie unless I also installed Soapy from Github

Did you install the development packages from the repo libsoapysdr-dev?

My suggestion is to:

1) use apt repo for library and some modules, build sources modules that are not in the repo
2) or use all source builds for the main library and modules and remove anything from apt repo
