### ISSUE TITLE
Low bandwidth

### ISSUE THREAD

**Issue by hellmind** [pothosware/SoapyRemote#41]
Is there a way to configure it to use a little bandwidth?
My rtl got its lower sample limit 250000hz  so thats like 5mbits
Is there a way to configure  soapyremot to filter that upstream to send 50khz only?

**Comment by guruofquality** [comment]
If its not already a rate supported by SoapyRTLSDR, I recommend adding a special mode to SoapyRTLSDR that takes the lower sample rate as a parameter and implements a decimation filter in the readStream call. https://github.com/pothosware/SoapyRTLSDR
