### ISSUE TITLE
SoapyRPCSocket::close never set _lastErrorMsg

### ISSUE THREAD

**Issue by hhrhhr** [pothosware/SoapyRemote#43]
if `SoapyRPCSocket::close()` fail, then `this->lastErrorMsg()` return an empty string.

https://github.com/pothosware/SoapyRemote/blob/f2e51b309016324fb4f2399b9333046b0884c396/common/SoapyRPCSocket.cpp#L91

how about `SOCKET_ERRNO`?
```
        SoapySDR::logf(SOAPY_SDR_ERROR, "SoapyRPCSocket::~SoapyRPCSocket: %d", SOCKET_ERRNO);
```

**Comment by guruofquality** [comment]
good catch https://github.com/pothosware/SoapyRemote/commit/8c23b1c2fd34fc7f20e42391ff4a50584d3f1628
