### ISSUE TITLE
>2MHz Bandwidth not possible

### ISSUE THREAD

**Issue by helioshk** [pothosware/SoapyRemote#47]
Hi,

I was trying to remotely operate an SDRplay, which would allow 10MHz bandwidth. At 2MHz channel bandwidth it runs very nice and smooth. But SoapyRemote doesn't seem to let a bigger bandwith through. 
When a bigger Bandwidth in CubicSDR is selected, the signal appears like after a 2MHz bandpass filter.

**Comment by guruofquality** [comment]
Are you saying that a specific setting is not properly going through the remote interface or are you implying that the sample rate is not sustainable? FWIW hardware is a big factor with sustainable sample rates. Many of the arm-based options on the server side tend to kick out after a few Msamps/s.

**Comment by helioshk** [comment]
I don't know what is limiting. As an example, this screenshot (CubicSDR) shows the spectrum from 8-12 MHz with a selected bandwith of 4 MHz.
![fft](https://user-images.githubusercontent.com/20465551/44550941-fcb2b980-a725-11e8-8db8-d320bdf46e83.png) but depending on the definition, only about 2 MHz make it through.
I don't think that the problem is CPU limitation (Usage is 44% of one core).

**Comment by guruofquality** [comment]
Im just trying to confirm that SoapyRemote is somehow causing this. When the sdrplay is plugged in directly to the PC (no SoapyRemote) do you observe the same behavior? Consequently, if SoapyRemote is somehow causing it and its correct when plugged in correctly, can you add some debug logging to SoapySDRPlay to confirm the expected bandwidth filter setting is at least being set?

**Comment by helioshk** [comment]
Ok that's embarassing. When starting it locally the problem also occurs.
Sorry for bothering you.

**Comment by SDRplay** [comment]
That plot is correct. Selecting a 4 MHz sample rate will mean that the IF bandwidth selected is 1.536 MHz, so what you are seeing there is the attenuation of the IF filter. If you select 5 MHz, then you will get a 5 MHz IF filter and see the entire spectrum.

**Comment by helioshk** [comment]
I wasn't aware that the IF bandwidth was adjustable. Where can I found information about this?

**Comment by SDRplay** [comment]
It's automatically selected depending on the sample rate. There are 8 settings in Zero IF mode - 0.2, 0.3, 0.6, 1.536, 5.0, 6.0, 7.0 and 8.0 MHz. The IF bandwidth selected will be equal to or lower than the sample rate selected. That's why 4 MHz sample rate selects 1.536 MHz IF filter.
