### ISSUE TITLE
Custom port when starting from systemd

### ISSUE THREAD

**Issue by SDRplay** [pothosware/SoapyRemote#54]
@guruofquality can you suggest a way to customise the port when starting the server via systemd?

@npaisnel is looking for this to autostart on RPi - the Odroid headless images I've produced all use the default port.

Thanks,

Andy.

**Comment by npaisnel** [comment]
Guessing I’ll eventually get an Odroid, they look damn good
But for now, just get the Pi working

Or even tell me what the default port is for SoapyRemote on the Pi

**Comment by guruofquality** [comment]
Edit the file and pass an argument to --bind https://github.com/pothosware/SoapyRemote/blob/master/system/SoapySDRServer.service.in#L7 example `--bind="0.0.0.0:1234"` or `--bind="[::0]:1234"`

Thats the quick answer, going forward if this is a useful thing to do, it should be possible to provide a default conf file and include it with EnvironmentFile. So it just comes down to editing a conf file.

**Comment by guruofquality** [comment]
> Or even tell me what the default port is for SoapyRemote on the Pi

When a port isnt specified in the server or client, it assumes 55132:

```
//! The default bind port for the remote server
#define SOAPY_REMOTE_DEFAULT_SERVICE "55132"
```

**Comment by SDRplay** [comment]
I think a conf file is the way to go if possible. Thanks for the answer, this should help @npaisnel

**Comment by npaisnel** [comment]
55132 brilliant

if there is a default port I have no need to change it.

I did ask this question on the forum but no one knew.


Thank you
