### ISSUE TITLE
Crash with more than 31 network interfaces

### ISSUE THREAD

**Issue by chaplin89** [pothosware/SoapyRemote#79]
Hi, it seems to me there is a bug in the function [SoapyRPCSocket::selectRecvMultiple](https://github.com/pothosware/SoapyRemote/blob/2a7363e485745153aa80eee4f912d5abf2d4e6cc/common/SoapyRPCSocket.cpp#L480): for what I can see, the function is creating a mask on a 32bit integers using N bits, where N is the number of the sockets that is related to the network interfaces. 

Since the function is using signed 32 bit integers, 31 interfaces is the maximum possible. If that function returns a negative value, it's interpreted as an error by the caller.

Unfortuntely for me I'm using more than 31 interfaces (it'a thing related to cuttlefish, didn't had the time to investigate) and this is making the library crash badly.

Questions:
1) is my analysis correct?
2) are there any workaround I can use?
3) If my analysis is correct, how to fix that? If there was a way to filter out virtual network interfaces I think it would be a great starting point.

**Comment by guruofquality** [comment]
Can you try this branch? https://github.com/pothosware/SoapyRemote/tree/increase_select_multiple

**Comment by chaplin89** [comment]
Yes, it seems to work.
Thanks!

Before:
![Before](https://user-images.githubusercontent.com/2357260/82237632-44d03180-9936-11ea-9a1d-a7237bf19dd1.png)


After:
![After](https://user-images.githubusercontent.com/2357260/82237640-47328b80-9936-11ea-96c3-46a6e06b1405.png)
